function phpads_deliverActiveX(content) {document.write(content);}
var OA_output = new Array();
OA_output['width:700-950,_height:70-110,_rcgf-469-img|rcgf-adsense'] = '';
OA_output['width:700-950,_height:70-110,_rcgf-469-img|rcgf-adsense'] += '<'+'a href=\'http://decals.rcgroups.com/adclick.php?bannerid=12193&amp;zoneid=0&amp;source=Video+Piloting+%28FPV%2FRPV%29&amp;dest=http%3A%2F%2Fwww.hobbyking.com%2Fhobbyking%2Fstore%2FRC_PRODUCT_SEARCH.asp%3FsearchType%3D10%26strSearch%3Dh.a.l%26nearby%3Dyes%26idCategory%3D502%26sortBy%3DRelevant%26NumPerPage%3D20%26currentPage%3D%26utm_source%3Drcgroups.com%26utm_medium%3Dbanner%26utm_campaign%3Dhal\' target=\'_blank\' onMouseOver="self.status=\'Turnigy H.A.L. Multirotor Frames\'; return true;" onMouseOut="self.status=\'\';return true;"><'+'img src=\'http://decals.rcgroups.net/storage/hal950x110_4.jpg\' width=\'950\' height=\'110\' alt=\'Turnigy H.A.L. Multirotor Frames\' title=\'Turnigy H.A.L. Multirotor Frames\' border=\'0\'><'+'/a>';
OA_output['clientid=2122'] = '';
OA_output['clientid=2122'] += '<'+'a href=\'http://decals.rcgroups.com/adclick.php?bannerid=5972&amp;zoneid=0&amp;source=Video+Piloting+%28FPV%2FRPV%29&amp;dest=http%3A%2F%2Fwww.hobbyking.com%2Fhobbyking%2Fstore%2FHobbyKing_New_RC_Products.asp%3ForderBy%3Drecently%26utm_source%3Drcgroups.com%26utm_medium%3Dbanner%26utm_campaign%3Dnewproducts\' target=\'_blank\'><'+'img src=\'http://decals.rcgroups.net/storage/middleimage_2.jpg\' width=\'354\' height=\'25\' alt=\'HobbyKing\' title=\'HobbyKing\' border=\'0\'><'+'/a>';
OA_output['zone:185'] = '';
OA_output['zone:185'] += '<'+'a href=\'http://decals.rcgroups.com/adclick.php?bannerid=11931&amp;zoneid=185&amp;source=Video+Piloting+%28FPV%2FRPV%29&amp;dest=http%3A%2F%2Fwww.tslrs.com\' target=\'_blank\' onMouseOver="self.status=\'ORDER HERE\'; return true;" onMouseOut="self.status=\'\';return true;"><'+'img src=\'http://decals.rcgroups.net/storage/ban2.gif\' width=\'450\' height=\'110\' alt=\'Tx700 Comming SOON!!\' title=\'Tx700 Comming SOON!!\' border=\'0\'><'+'/a>';
OA_output['zone:187'] = '';
OA_output['zone:187'] += '<'+'a href=\'http://decals.rcgroups.com/adclick.php?bannerid=11235&amp;zoneid=187&amp;source=Video+Piloting+%28FPV%2FRPV%29&amp;dest=http%3A%2F%2Fwww.readymaderc.com%2Fstore%2Findex.php%3Fmain_page%3Dindex%26cPath%3D101%26utm_source%3Drcgroupsfpv%26utm_medium%3Dbanner%26utm_campaign%3Dpenguin\' target=\'_blank\' onMouseOver="self.status=\'Check Us Out at ReadyMadeRC.com!\'; return true;" onMouseOut="self.status=\'\';return true;"><'+'img src=\'http://decals.rcgroups.net/storage/copy-of-penguin-rcgroups-banner_256.gif\' width=\'450\' height=\'110\' alt=\'Check Out the Universeye Penguin FPV Plane at ReadyMadeRC.com!\' title=\'Check Out the Universeye Penguin FPV Plane at ReadyMadeRC.com!\' border=\'0\'><'+'/a>';
OA_output['zone:98'] = '';
OA_output['zone:170'] = '';
OA_output['zone:170'] += '<'+'script type="text/javascript"><'+'!--\ngoogle_ad_client = "ca-pub-3653278693006306";\ngoogle_ad_slot = "7862456075";\ngoogle_ad_width = 728;\ngoogle_ad_height = 90;\n//-->\n<'+'/script>\n<'+'script type="text/javascript"\nsrc="http://pagead2.googlesyndication.com/pagead/show_ads.js">\n<'+'/script>';
OA_output['clientid=1004'] = '';
OA_output['clientid=1004'] += '<'+'a href=\'http://decals.rcgroups.com/adclick.php?bannerid=6814&amp;zoneid=0&amp;source=Video+Piloting+%28FPV%2FRPV%29&amp;dest=http%3A%2F%2Fwww.castlecreations.com%2Fproducts%2Fcastle_connectors.html\' target=\'_blank\' onMouseOver="self.status=\'Castle Connectors\'; return true;" onMouseOut="self.status=\'\';return true;"><'+'img src=\'http://decals.rcgroups.net/storage/castle-mid-connectors.jpg\' width=\'442\' height=\'30\' alt=\'Castle Connectors\' title=\'Castle Connectors\' border=\'0\'><'+'/a>';
